common_param: &shared
  L: 0.433
  W: 0.12
  H: 0.05
  L1: 0.087
  L2: 0.25
  L3: 0.25
  m : 20
  m_hip : 0.3
  m_thigh : 0.143
  m_calf : 0.1
  Ixx : 0.01
  Iyy : 0.01
  Izz : 0.01
  Izz_thigh : 0.01
  Izz_calf : 0.01
  num_legs: 4

leg_controller:
  ros__parameters:
    <<: *shared



